fix dictify function to handle Tensors
microsoft/syntheseus pull request #99
Opened 2024-08-31 13:13 UTC by mrwnmsr

PR fixes that the `dictify` function does not handle tensors, which can be needed in some occasions.

2024-09-02 21:09 UTC, AustinT approved these changes
LGTM. I think the ruff error in pre-commit might be fixed by introducing a blank line after line 9 (to separate built-in modules from third-party ones).

2024-09-02 22:51 UTC, kmaziarz requested changes
I think this will fail the tests, because the core of the library is supposed to run without optional dependencies such as `torch`. But equally, I don't think we really need to support tensors here. This came up because one of our internal models had a bug and was returning its prediction probability as a tensor. The solution isn't to support tensors in `dictify` but rather fix the model 🙂 All of the models in syntheseus return their outputs as plain Python datatypes and I think we can keep it that way.

2024-09-03 10:25 UTC, AustinT commented
Good catch Kris, sorry I completely forgot about not supporting torch as a top-level import. Lesson: don't review PRs when I am very tired 🥲
________________________________
From: Krzysztof Maziarz ***@***.***>
Sent: September 2, 2024 11:51 PM
To: microsoft/syntheseus ***@***.***>
Cc: Austin Tripp ***@***.***>; Review requested ***@***.***>
Subject: Re: [microsoft/syntheseus] fix dictify function to handle Tensors (PR #99)


@kmaziarz requested changes on this pull request.

I think this will fail the tests, because the core of the library is supposed to run without optional dependencies such as torch. But equally, I don't think we really need to support tensors here. This came up because one of our internal models had a bug and was returning its prediction probability as a tensor. The solution isn't to support tensors in dictify but rather fix the model 🙂 All of the models in syntheseus return their outputs as plain Python datatypes and I think we can keep it that way.

—
Reply to this email directly, view it on GitHub<https://github.com/microsoft/syntheseus/pull/99#pullrequestreview-2276188403>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AFNTKE6B4PSGOZ7QLPZQV7LZUTTXPAVCNFSM6AAAAABNN3ZKPWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENZWGE4DQNBQGM>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-09-09 11:44 UTC, mrwnmsr commented
lets close this then

2024-09-09 11:44 UTC, closed without merging